### ISSUE TITLE
Cannot reach the server after generate output for somewhile

### ISSUE THREAD

**Issue by JasonFeng02** [smallcloudai/refact-self-hosting#12]
![image](https://github.com/smallcloudai/refact-self-hosting/assets/92613744/8a804894-42c2-480f-99d9-4c6c3e52ce71)
![image](https://github.com/smallcloudai/refact-self-hosting/assets/92613744/a8c818b9-34c6-4fb3-b170-d7dc2c631f78)

**Comment by mitya52** [comment]
@JasonFeng02 did you use starcoder model?

**Comment by JasonFeng02** [comment]
no,I'm using CONTRASTcode/3b/multi model

**Comment by mitya52** [comment]
it might be a bug with webserver
we are working on fix now, it takes about 1-2 days

**Comment by mitya52** [comment]
@JasonFeng02 update plugin and image to latest versions, it should help you with issue
