### ISSUE TITLE
Deselect SVG by default

### ISSUE THREAD

**Issue by k3KAW8Pnf7mkmdSMPHz27** [smallcloudai/refact-self-hosting#24]
I can't verify that these are image files, but they are selected by default, and probably shouldn't be.

Source: https://github.com/JabRef/jabref.git

![image](https://github.com/smallcloudai/refact-self-hosting/assets/2598631/6485b29b-9a8f-4139-b96b-e223036c1ef1)

**Comment by olegklimov** [comment]
Next version will have 15 file types off by default 👍

**Comment by olegklimov** [comment]
Fixed
