### ISSUE TITLE
Problem with --env as last part of command on powershell

### ISSUE THREAD

**Issue by pixellos** [smallcloudai/refact-self-hosting#9]
Hi,

`docker run -p 8008:8008 --gpus 0 --name refact_self_hosting smallcloud/refact_self_hosting --env SERVER_API_TOKEN=$token`

Doesn't work on windows 11 powershel , but

`docker run --env SERVER_API_TOKEN=$token -p 8008:8008 --gpus 0 --name refact_self_hosting smallcloud/refact_self_hosting `

Works just fine. Here is reference why it's happening https://stackoverflow.com/a/64159568
May be good to update the docs to include that.

**Comment by mitya52** [comment]
sorry for that, readme changes backed out
stay tune for updated version without api key usage
